core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='home'),
]


listings/urls.py
from django.urls import path
from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings_page, name='listings_page'), # Main listings
    path('create/', views.create_listing, name='create_listing'),
    path('<slug:slug>/', views.listing_detail, name='listing_detail'),
    path('<slug:slug>/edit/', views.edit_listing, name='edit_listing'),
    path('<slug:slug>/delete/', views.delete_listing, name='delete_listing'),
    path('<slug:slug>/inquire/', views.inquiry_view, name='inquiry'), 
    path('<slug:slug>/book/', views.booking_view, name='booking'),

]



renthub/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from listings import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', views.register, name='register'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.BASE_DIR / 'static')
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


users/urls.py
# users/urls.py

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('rentee_dashboard/', views.rentee_dashboard, name='rentee_dashboard'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rental Platform</title> 
</head>
<body>
    <nav>
        <a href="{% url 'home' %}">Home</a> |
        <a href="{% url 'listings:listings_page' %}">Listings</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'users:dashboard' %}">Dashboard</a> |
            <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Login</a> |
            <a href="{% url 'register' %}">Register</a>
        {% endif %}
    </nav>
    <hr>

    {% if messages %}
      {% for message in messages %}
        <p style="color: green;">{{ message }}</p>
      {% endfor %}
    {% endif %}

    {% block content %}
    <!-- Page content will go here -->
    {% endblock %}
</body>
</html>